// Shared location suggestion list used across post creation, lost & found, etc.
export const LOCATION_SUGGESTIONS: string[] = [
  'Goa, India', 'Kerala, India', 'Ladakh, India', 'Rishikesh, Uttarakhand, India', 'Manali, Himachal Pradesh, India',
  'Hampi, Karnataka, India', 'Mumbai, Maharashtra, India', 'Delhi, India', 'Jaipur, Rajasthan, India',
  'Dharamshala, Himachal Pradesh, India', 'Shimla, Himachal Pradesh, India', 'McLeod Ganj, Himachal Pradesh, India',
  'Kasol, Himachal Pradesh, India', 'Dalhousie, Himachal Pradesh, India', 'Spiti Valley, Himachal Pradesh, India',
  'Udaipur, Rajasthan, India', 'Jodhpur, Rajasthan, India', 'Pushkar, Rajasthan, India',
  'Varanasi, Uttar Pradesh, India', 'Agra, Uttar Pradesh, India', 'Lucknow, Uttar Pradesh, India',
  'Darjeeling, West Bengal, India', 'Kolkata, West Bengal, India', 'Gangtok, Sikkim, India',
  'Shillong, Meghalaya, India', 'Cherrapunji, Meghalaya, India', 'Tawang, Arunachal Pradesh, India',
  'Coorg, Karnataka, India', 'Mysore, Karnataka, India', 'Bangalore, Karnataka, India',
  'Pondicherry, India', 'Ooty, Tamil Nadu, India', 'Kodaikanal, Tamil Nadu, India', 'Chennai, Tamil Nadu, India',
  'Munnar, Kerala, India', 'Alleppey, Kerala, India', 'Kochi, Kerala, India', 'Wayanad, Kerala, India',
  'Leh, Ladakh, India', 'Nubra Valley, Ladakh, India', 'Pangong Lake, Ladakh, India',
  'Amritsar, Punjab, India', 'Chandigarh, India', 'Mussoorie, Uttarakhand, India', 'Nainital, Uttarakhand, India',
  'Haridwar, Uttarakhand, India', 'Auli, Uttarakhand, India', 'Jim Corbett, Uttarakhand, India',
  'Pune, Maharashtra, India', 'Lonavala, Maharashtra, India', 'Mahabaleshwar, Maharashtra, India',
  'Hyderabad, Telangana, India', 'Visakhapatnam, Andhra Pradesh, India',
  'Andaman Islands, India', 'Lakshadweep, India', 'Mount Abu, Rajasthan, India',
  'Paris, France', 'Nice, France', 'Lyon, France', 'Marseille, France',
  'Tokyo, Japan', 'Kyoto, Japan', 'Osaka, Japan',
  'Bali, Indonesia', 'Jakarta, Indonesia',
  'New York, USA', 'Los Angeles, USA', 'San Francisco, USA', 'Miami, USA',
  'London, UK', 'Edinburgh, UK', 'Manchester, UK',
  'Dubai, UAE', 'Abu Dhabi, UAE',
  'Barcelona, Spain', 'Madrid, Spain',
  'Rome, Italy', 'Venice, Italy', 'Florence, Italy', 'Milan, Italy',
  'Bangkok, Thailand', 'Phuket, Thailand', 'Chiang Mai, Thailand',
  'Singapore', 'Sydney, Australia', 'Melbourne, Australia',
  'Maldives', 'Sri Lanka', 'Nepal', 'Bhutan',
  'Istanbul, Turkey', 'Cappadocia, Turkey',
  'Amsterdam, Netherlands', 'Prague, Czech Republic', 'Vienna, Austria',
  'Zurich, Switzerland', 'Interlaken, Switzerland',
  'Cairo, Egypt', 'Marrakech, Morocco', 'Cape Town, South Africa',
  'Rio de Janeiro, Brazil', 'Cancun, Mexico',
];
