import React from 'react';
import { Sparkles, Users, MapPin, Shield, Wallet, Calendar, WifiOff, MessageCircle, ArrowRight } from 'lucide-react';

interface FeaturesSectionProps {
  onNavigate?: (section: string) => void;
  isLoggedIn?: boolean;
}

const FeaturesSection: React.FC<FeaturesSectionProps> = ({ onNavigate, isLoggedIn }) => {
  const features = [
    {
      icon: Sparkles,
      title: 'AI Smart Itinerary',
      description: 'Get personalized day-wise travel plans with cost breakdowns, generated by our intelligent AI based on your preferences.',
      color: 'from-primary to-accent',
      section: 'itinerary',
      preview: '🗓️ 5-Day Goa Plan • ₹18,000 Budget • Beaches, Culture & Food',
    },
    {
      icon: Users,
      title: 'Travel Match Score',
      description: 'Find compatible travel buddies with our AI matching algorithm that considers budget, personality, and interests.',
      color: 'from-secondary to-sunset-pink',
      section: 'explore',
      preview: '👥 92% Match • Similar budget & interests • Verified profiles',
    },
    {
      icon: MapPin,
      title: 'Nearby Discovery',
      description: 'Discover travelers within 1-25km radius. Connect with like-minded adventurers in your area.',
      color: 'from-ocean to-primary',
      section: 'explore',
      preview: '📍 6 travelers near you • Arjun (4.8km) • 92% match',
    },
    {
      icon: Shield,
      title: 'Emergency SOS',
      description: 'One-tap emergency alerts, live location sharing, and quick access to nearby hospitals and police stations.',
      color: 'from-destructive to-sunset-pink',
      section: null,
      preview: '🚨 One-tap SOS • Live location • Nearest hospital: 2.3km',
    },
    {
      icon: Wallet,
      title: 'Group Expense Split',
      description: 'Auto-split expenses among group members with UPI integration. Track who owes whom easily.',
      color: 'from-success to-primary',
      section: 'expenses',
      preview: '💰 ₹20,100 Total • You owe ₹2,800 • Pay via UPI instantly',
    },
    {
      icon: MessageCircle,
      title: 'Secure Messaging',
      description: 'Chat with verified travelers. Messaging enabled only after mutual acceptance for safety.',
      color: 'from-accent to-secondary',
      section: null,
      preview: '💬 Request-based chat • Verified users only • End-to-end safe',
    },
    {
      icon: WifiOff,
      title: 'Offline Survival',
      description: 'Access saved maps, itineraries, and emergency contacts even without internet connection.',
      color: 'from-muted-foreground to-foreground',
      section: null,
      preview: '📶 Saved maps & contacts • Works without internet',
    },
    {
      icon: Calendar,
      title: 'Trip Planning',
      description: 'Plan complete trips with destinations, activities, accommodation, and budget management.',
      color: 'from-primary to-ocean',
      section: 'itinerary',
      preview: '✈️ Destination + Activities + Stay + Budget = Perfect Trip',
    },
  ];

  return (
    <section className="py-20 lg:py-32 bg-gradient-to-b from-background to-muted/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 rounded-full text-primary text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />
            Powered by AI
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-6">
            Everything You Need for
            <span className="text-gradient"> Smart Travel</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            From AI-powered planning to emergency safety features, TripSync has everything to make your travels smarter, safer, and more social.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map(({ icon: Icon, title, description, color, section, preview }) => (
            <div
              key={title}
              onClick={() => {
                if (section && onNavigate) {
                  if (isLoggedIn) {
                    onNavigate(section);
                  } else {
                    onNavigate('login');
                  }
                }
              }}
              className={`group p-6 bg-card rounded-2xl border border-border hover:border-primary/30 hover:shadow-xl transition-all duration-300 ${section ? 'cursor-pointer' : ''}`}
            >
              <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center mb-5 shadow-lg group-hover:scale-110 transition-transform`}>
                <Icon className="w-7 h-7 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">{title}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed mb-3">{description}</p>
              
              {/* Preview snippet */}
              <div className="p-3 bg-muted/50 rounded-xl border border-border/50 group-hover:bg-primary/5 transition-colors">
                <p className="text-xs text-muted-foreground leading-relaxed">{preview}</p>
              </div>
              
              {section && (
                <div className="flex items-center gap-1 mt-3 text-xs font-medium text-primary opacity-0 group-hover:opacity-100 transition-opacity">
                  <span>Explore</span>
                  <ArrowRight className="w-3 h-3" />
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
